main: net.iamvishnu.BirthdayBoy.BirthdayBoy
name: BirthdayBoy
version: 0.0.1
author: IAMVISHNU Media
description: A Birthday tracker and age gater
commands:
    mycommand:
    description: An example command
    usage: /mycommand
    permission: myplugin.mycommand
    permission-message: You don't have the myplugin.mycommand permission.